name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build app
        run: ./scripts/buildprod.sh  

      #add goose and migration up
      - name: install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: run migration
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: deploy docker image
        run: "gcloud builds submit --tag us-east1-docker.pkg.dev/notely-419420/notely-ar-repo/notely:first"
 
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-east1-docker.pkg.dev/notely-419420/notely-ar-repo/notely:first --region us-central1 --allow-unauthenticated --project notely-419420 --max-instances=4
